version: 0.0
os: linux
files:
 - source: /
   destination: /
hooks:
  Install:
    - location: setup.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 3600
      runas: root
